### PR TITLE
fix the wrong import path

### PR DESCRIPTION
**Pull request by fzerorubigd**
I don't think its correct to use this import path in project, since any project with postgres driver, already include a proper version of this library.

### CODE REVIEW

**Comment by kevinburkeshyp** [comment]
Crap, I didn't think about that. Good catch. 

I think we need to delete the Godeps directory altogether and revert the module paths.

**Comment by fzerorubigd** [comment]
Currently its not a problem since importing this, do not import anything  except pq driver.

**Comment by kevinburkeshyp** [comment]
Right, but if we're removing the dependencies from it, we should just delete the whole directory

**Comment by kevinburkeshyp** [comment]
LGTM! Thanks!

**Comment by kevinburkeshyp** [comment]
Just pushed tag 0.4 with this change.

**Pull request merged**
